// <auto-generated />
using ApiNegozio.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiNegozio.Migrations
{
    [DbContext(typeof(ProdottiNegozioContext))]
    partial class ProdottiNegozioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiNegozio.Models.Fornitore", b =>
                {
                    b.Property<int>("IdFrntr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFrntr"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdFrntr")
                        .HasName("PK__Fornitor__D40587492BF31CB4");

                    b.ToTable("Fornitore", (string)null);
                });

            modelBuilder.Entity("ApiNegozio.Models.Prodotto", b =>
                {
                    b.Property<int>("IdPrdt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrdt"), 1L, 1);

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("bit");

                    b.Property<byte>("Giacenza")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdPrdt")
                        .HasName("PK__Prodotto__E40DCE64BB4163F5");

                    b.ToTable("Prodotto", (string)null);
                });

            modelBuilder.Entity("ApiNegozio.Models.Taglia", b =>
                {
                    b.Property<int>("IdTaglia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaglia"), 1L, 1);

                    b.Property<string>("TagliaVestito")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("IdTaglia")
                        .HasName("PK__Taglia__7FFB1DAD06F2ABAE");

                    b.ToTable("Taglia");
                });

            modelBuilder.Entity("ApiNegozio.Models.TaglieFornitori", b =>
                {
                    b.Property<int>("IdTglFr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTglFr"), 1L, 1);

                    b.Property<int>("IdFrntr")
                        .HasColumnType("int");

                    b.Property<int>("IdPrdt")
                        .HasColumnType("int");

                    b.Property<int>("IdTaglia")
                        .HasColumnType("int");

                    b.HasKey("IdTglFr")
                        .HasName("PK__TaglieFo__BCC26CBE221E0865");

                    b.HasIndex("IdFrntr");

                    b.HasIndex("IdPrdt");

                    b.HasIndex("IdTaglia");

                    b.ToTable("TaglieFornitori", (string)null);
                });

            modelBuilder.Entity("ApiNegozio.Models.TaglieFornitori", b =>
                {
                    b.HasOne("ApiNegozio.Models.Fornitore", "IdFrntrNavigation")
                        .WithMany("TaglieFornitori")
                        .HasForeignKey("IdFrntr")
                        .IsRequired()
                        .HasConstraintName("FK_TaglieFornitori_Fornitore");

                    b.HasOne("ApiNegozio.Models.Prodotto", "IdPrdtNavigation")
                        .WithMany("TaglieFornitori")
                        .HasForeignKey("IdPrdt")
                        .IsRequired()
                        .HasConstraintName("FK_TaglieFornitori_Prodotto");

                    b.HasOne("ApiNegozio.Models.Taglia", "IdTagliaNavigation")
                        .WithMany("TaglieFornitori")
                        .HasForeignKey("IdTaglia")
                        .IsRequired()
                        .HasConstraintName("FK_TaglieFornitori_Taglia");

                    b.Navigation("IdFrntrNavigation");

                    b.Navigation("IdPrdtNavigation");

                    b.Navigation("IdTagliaNavigation");
                });

            modelBuilder.Entity("ApiNegozio.Models.Fornitore", b =>
                {
                    b.Navigation("TaglieFornitori");
                });

            modelBuilder.Entity("ApiNegozio.Models.Prodotto", b =>
                {
                    b.Navigation("TaglieFornitori");
                });

            modelBuilder.Entity("ApiNegozio.Models.Taglia", b =>
                {
                    b.Navigation("TaglieFornitori");
                });
#pragma warning restore 612, 618
        }
    }
}
